export const CREATE_COURSE = 'CREATE_COURSE';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

